<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AtkCategory;
use App\Models\AtkItem;
use App\Models\AtkTeam;

class AtkSeeder extends Seeder
{
    public function run(): void
    {
        // ATK Teams
        $teams = ['distribusi', 'produksi', 'ipds', 'nerwilis', 'sosial umum'];
        foreach ($teams as $team) {
            AtkTeam::firstOrCreate(['name' => $team]);
        }

        // ATK Categories & Items
        $data = [
            ['Alat Tulis', 'Ballpoint Standart AE-7 Fine Black', 'Buah'],
            ['Alat Tulis', 'Ballpoint Standart AE-7 Fine Red', 'Buah'],
            ['Alat Tulis', 'Spidol Snowman Permanen G-520 Biru', 'Buah'],
            ['Alat Tulis', 'Isi Pensil Mekanik Pilot PPL-0.5 2B', 'Tube'],
            ['Alat Tulis', 'Isi Pensil Mekanik Debozz 0.5 2B', 'Tube'],
            ['Alat Tulis', 'Ballpoint Sarasa 0.7 Merah', 'Buah'],
            ['Alat Tulis', 'Ballpoint Sarasa 0.7 Hitam', 'Buah'],
            ['Alat Tulis', 'Pensil 2B Faber Castell', 'Buah'],
            ['Alat Tulis', 'Pensil Mekanik Pilot Japan 0.5 H-165', 'Buah'],
            ['Alat Tulis', 'Refill Pentel Hitam', 'Buah'],
            ['Alat Tulis', 'Ballpoint Sarasa Hitam', 'Buah'],
            ['Alat Tulis', 'Spidol Snowman Permanent G-12 Hitam', 'Buah'],
            ['Alat Tulis', 'Spidol Snowman Permanent G-12 Biru', 'Buah'],
            ['Alat Tulis', 'Spidol Snowman Permanent G-12 Merah', 'Buah'],
            ['Alat Tulis', 'Isi Ballpoint Pentel', 'Buah'],
            ['Alat Tulis', 'Ballpoint Kokoro', 'Buah'],
            ['Alat Tulis', 'Spidol Snowman Permanen G-520 Hitam', 'Buah'],
            ['Penjepit Kertas', 'Binder Clip Joyko No.105', 'Box'],
            ['Penjepit Kertas', 'Paper Clip Jumbo No.5 Kenko', 'Box'],
            ['Penjepit Kertas', 'Paper Clip No.1 Kenko', 'Box'],
            ['Penjepit Kertas', 'Binder Clip 105 Kenko', 'Box'],
            ['Penjepit Kertas', 'Binder Clip 107 Kenko', 'Box'],
            ['Penjepit Kertas', 'Binder Clip 111 Kenko', 'Box'],
            ['Penjepit Kertas', 'Binder Clip 155 Kenko', 'Box'],
            ['Penjepit Kertas', 'Binder Clip 200 Kenko', 'Box'],
            ['Penjepit Kertas', 'Binder Clip 260 Kenko', 'Buah'],
            ['Penjepit Kertas', 'Binder Clip 280 Kenko', 'Buah'],
            ['Penjepit Kertas', 'Binder Clip 300 Kenko', 'Buah'],
            ['Penghapus / Korektor', 'Penghapus Faber Castell Putih', 'Buah'],
            ['Penghapus / Korektor', 'Penghapus Faber Castell Hitam', 'Buah'],
            ['Penghapus / Korektor', 'Tipe-X Kenko KE-01 Merah', 'Buah'],
            ['Ordner / Map', 'Snelhecter Plastik', 'Buah'],
            ['Ordner / Map', 'Stopmap Berlogo ST2023', 'Buah'],
            ['Ordner / Map', 'Ordner Forte Enduro 75 mm Hitam', 'Buah'],
            ['Ordner / Map', 'Ordner Forte Enduro 50 mm Hitam', 'Buah'],
            ['Ordner / Map', 'Map Berlogo SE2026', 'Buah'],
            ['Ordner / Map', 'Snelhecter Plastik', 'Buah'],
            ['Ordner / Map', 'Map Amplop Plastik Kancing Jenia', 'Buah'],
            ['Ordner / Map', 'Map Zipper 9001', 'Buah'],
            ['Ordner / Map', 'Stopmap Folio Kertas', 'Buah'],
            ['Ordner / Map', 'Map Amplop Plastik Kancing Jenia', 'Buah'],
            ['Ordner / Map', 'Map Tenteng / Zipper Bag Tofla Brief Bag 3080', 'Buah'],
            ['Ordner / Map', 'Business File Big', 'Buah'],
            ['Ordner / Map', 'Spring File', 'Buah'],
            ['Ordner / Map', 'Map Plastik', 'Buah'],
            ['Ordner / Map', 'Stopmap Ivory Berlogo SE2026', 'Buah'],
            ['Ordner / Map', 'Pocket Expanding File A4', 'Buah'],
            ['Ordner / Map', 'Ordner Forte Enduro F4 75 mm', 'Buah'],
            ['Penggaris', 'Penggaris Besi Kenko 30 cm', 'Buah'],
            ['Penggaris', 'Penggaris Besi Joyko 30 cm', 'Buah'],
            ['Cutter / Gunting / Rautan', 'Cutter Bazic L-500', 'Buah'],
            ['Cutter / Gunting / Rautan', 'Cutter Joyko L-500', 'Buah'],
            ['Cutter / Gunting / Rautan', 'Gunting Besar Gunindo KC-888', 'Buah'],
            ['Cutter / Gunting / Rautan', 'Rautan Kecil Faber Castell', 'Buah'],
            ['Cutter / Gunting / Rautan', 'Gunting Ideal K-300', 'Buah'],
            ['Alat Perekat', 'Lakban Coklat Nachi 2 Inch', 'Buah'],
            ['Alat Perekat', 'Lem Povinal 111 K', 'Buah'],
            ['Alat Perekat', 'Lem Povinal Sedang 75 ml', 'Buah'],
            ['Alat Perekat', 'Lakban Hitam Besar', 'Buah'],
            ['Alat Perekat', 'Double Tape', 'Buah'],
            ['Alat Perekat', 'Isolasi Kecil', 'Buah'],
            ['Alat Perekat', 'Lakban Kertas 1 Inch', 'Buah'],
            ['Alat Perekat', 'Lem Stick Kenko', 'Buah'],
            ['Alat Perekat', 'Lakban Bening', 'Buah'],
            ['Stapler', 'Stapler Max HD-10D', 'Buah'],
            ['Stapler', 'Stapler Max HD-10', 'Buah'],
            ['Stapler', 'Stapler Joyko HD-10D', 'Buah'],
            ['Stapler', 'Stapler Joyko HD-10', 'Buah'],
            ['Isi Stapler', 'Isi Staples 23/24', 'Doz'],
            ['Isi Stapler', 'Isi Staples 23/15', 'Doz'],
            ['Isi Stapler', 'Refill Stapler Max HD-10D', 'Doz'],
            ['Isi Stapler', 'Refill Staples Max No.3-1M', 'Doz'],
            ['Isi Stapler', 'Refill Staples Kangaro No.10-1M', 'Doz'],
            ['Sticky Notes', 'Post-It 51 x 38', 'Pcs'],
            ['Sticky Notes', 'Post-It 76 x 76 Color', 'Pcs'],
            ['Sticky Notes', 'Post-It 76 x 51 Color', 'Pcs'],
            ['Sticky Notes', 'Post-It Index 5 Warna', 'Pcs'],
            ['Sticky Notes', 'Sticky Note Rainbow 5 Warna', 'Pcs'],
            ['Kertas HVS', 'Kertas A4 80 gsm Sidu', 'Rim'],
            ['Kertas HVS', 'Kertas A3 80 gsm Sidu', 'Rim'],
            ['Kertas HVS', 'Kertas F4 70 gsm Sidu', 'Rim'],
            ['Kertas HVS', 'Kertas A4 70 gsm Sidu', 'Rim'],
            ['Amplop', 'Amplop 11 x 24 Kw7', 'Lembar'],
            ['Amplop', 'Amplop Plastik Kancing Jenia', 'Buah'],
            ['Amplop', 'Amplop 110 x 70 mm Merpati 80 gsm', 'Lembar'],
            ['Amplop', 'Amplop 114 x 162 mm Paperline', 'Lembar'],
            ['Amplop', 'Amplop Buklet 110 x 230 mm Paperline', 'Box'],
            ['Amplop', 'Amplop Coklat Samson Fox 12 x 28 cm', 'Box'],
            ['Amplop', 'Amplop Coklat Berlogo SE2026', 'Buah'],
            ['Amplop', 'Amplop Coklat Tanggung Berlogo BPS', 'Buah'],
            ['Amplop', 'Amplop Coklat Besar Berlogo BPS', 'Buah'],
            ['Amplop', 'Amplop Coklat Besar Polos', 'Buah'],
            ['Amplop', 'Amplop Putih Besar Paperline No.90', 'Lembar'],
            ['Tinta / Toner Printer', 'Toner 30A', 'Buah'],
            ['Tinta / Toner Printer', 'Toner 32A', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 15160 C', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 15160 M', 'Buah'],
            ['Tinta / Toner Printer', 'Toner 192A', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 001 Black', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 001 Cyan', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 001 Magenta', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 001 Yellow', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 008 Magenta', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box C9345 PXMB9', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box T6711 PXMB3', 'Buah'],
            ['Tinta / Toner Printer', 'Toner CT 93A + CIP', 'Buah'],
            ['Tinta / Toner Printer', 'Cartridge Toner 93A', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box TC9345', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 008 Cyan', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta 008 Yellow', 'Botol'],
            ['Tinta / Toner Printer', 'Maintenance Box Epson L6170', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box L15150 / L15160', 'Buah'],
            ['Tinta / Toner Printer', 'Toner 92A / 93A', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L15160 Black 008', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L15160 Cyan 008', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L15160 Magenta 008', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L15160 Yellow 008', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L6170 Black 001', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L6170 Cyan 001', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L6170 Magenta 001', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L6170 Yellow 001', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box EWMB2', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box Epson PXMB9', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L1455 Black 774', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L1455 Cyan 664', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L1455 Magenta 664', 'Buah'],
            ['Tinta / Toner Printer', 'Tinta Epson L1455 Yellow 664', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box T6711 / PXMB3', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box L15160', 'Buah'],
            ['Tinta / Toner Printer', 'Maintenance Box Epson L1455', 'Buah'],
            ['Tinta / Toner Printer', 'Toner 26A', 'Buah'],
            ['Tinta / Toner Printer', 'Toner 92A / 93A', 'Buah'],
            ['Tinta / Toner Printer', 'Cartridge Compatible 26A Amazink', 'Buah'],
            ['Batu Baterai', 'Baterai Alkaline AAA', 'Pak'],
            ['Batu Baterai', 'Baterai Alkaline AA (4+2)', 'Pak'],
            ['Lainnya', 'Tali Rafia Hitam Bola Dunia', 'Roll'],
            ['Lainnya', 'Pen Stand V-Tec', 'Buah'],
            ['Lainnya', 'File Box Lion Star Susun 4 Mini', 'Buah'],
            ['Lainnya', 'Karet Gelang', 'Pak'],
            ['Lainnya', 'Bantalan Stempel', 'Buah'],
        ];

        foreach ($data as [$category, $name, $satuan]) {
            $cat = AtkCategory::firstOrCreate(['name' => $category]);
            AtkItem::firstOrCreate(
                ['category_id' => $cat->id, 'name' => $name],
                ['satuan' => $satuan]
            );
        }
    }
}
